name: CI/CD - Vulnado

on:
  push:
    branches:
      - master

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  build:
    uses: skacode/org/.github/workflows/cicd-template.yml@main
    with:
      project_name: "Vulnado"
      docker_image: "skacode/vulnado:latest"
      working_directory: "."
    secrets: inherit
